### ISSUE TITLE
Permission denied when i click to export an tjp file from an project.

### ISSUE THREAD

**Issue by lujianmei** [chris2fr/redmine_taskjuggler#47]
I got this error when i finish install the plugin into Redmine, and click the tab on a project page.
'''
Started GET "/redmine/redmine_taskjuggler_projects/office" for 127.0.0.1 at 2015-11-11 22:29:51 +0800
Processing by RedmineTaskjugglerProjectsController#show as HTML
  Parameters: {"id"=>"office"}
  Current user: kevin (id=1)
  Rendered plugins/redmine_taskjuggler/app/views/redmine_taskjuggler_projects/show.html.erb within layouts/base (3.9ms)
Completed 500 Internal Server Error in 14ms (ActiveRecord: 1.7ms)

ActionView::Template::Error (Permission denied - office-0_0_0.tjp.log):
    89:  
    90:     <% Dir.chdir Setting.plugin_redmine_taskjuggler["tjp_path"] %>
    91: 
    92:         <% File.open("#{name_file}.log", 'w') {|file| file.truncate(0)} %>
    93: 
    94:         <% `LANG=ru_RU.UTF-8 tj3 --silent #{name_file} > #{name_file}.log 2>&1` %>
    95: 
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
'''

I use bitnami redmime 3.1.1, and use the latest version of this plugin, on a archlinux platform.
The plugin install was complete without an error, and the account for startup bitnami is a nomal user, not root. It seems when i clicked on export the tjp file, and the file can not be created by this user.

Sorry that i do not know what is wrong, and i am not good at ruby.
Please help to check it.

![Uploading Selection_103.png…]()

**Comment by lujianmei** [comment]
Server Path for TaskJuggler Creation (must have trailing slash)	, the value i typed in: /usr/bin/

**Comment by lujianmei** [comment]
Also there is a issue on this page:
http://www.test.com:8080/redmine/settings/plugin/redmine_taskjuggler

When i click on "TJ Teams can be administered here." it will goto: "http://www.test.com:8080/redmine_taskjuggler_teams", as you can see, the url might be: "http://www.test.com:8080/redmine/redmine_taskjuggler_teams"
It seems the abstract link is not ok.

**Comment by chris2fr** [comment]
Hi,

I am sorry to have missed the first post. It seems like a permission error to the place the log file. 

My Skype is christopher_mann. I can help you with your installation if you would like. There are both technical and organizational challenges here. 

Allow me some time to remember exactly what is going on, and I will get back to this issue within a few hours. It seems that you also have improvements.

Thank you for your dedication and I will get back to you on this,

Christopher

**Comment by lujianmei** [comment]
Thanks, the first post followed:



I got this error when i finish install the plugin into Redmine, and click the tab on a project page.
'''
Started GET "/redmine/redmine_taskjuggler_projects/office" for 127.0.0.1 at 2015-11-11 22:29:51 +0800
Processing by RedmineTaskjugglerProjectsController#show as HTML
Parameters: {"id"=>"office"}
Current user: kevin (id=1)
Rendered plugins/redmine_taskjuggler/app/views/redmine_taskjuggler_projects/show.html.erb within layouts/base (3.9ms)
Completed 500 Internal Server Error in 14ms (ActiveRecord: 1.7ms)

ActionView::Template::Error (Permission denied - office-0_0_0.tjp.log):
89:

90: <% Dir.chdir Setting.plugin_redmine_taskjuggler["tjp_path"] %>
91: 
92: <% File.open("#{name_file}.log", 'w') {|file| file.truncate(0)} %>
93: 
94: <% LANG=ru_RU.UTF-8 tj3 --silent #{name_file} > #{name_file}.log 2>&1 %>
95: 
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
'''

I use bitnami redmime 3.1.1, and use the latest version of this plugin, on a archlinux platform.
The plugin install was complete without an error, and the account for startup bitnami is a nomal user, not root. It seems when i clicked on export the tjp file, and the file can not be created by this user.

Sorry that i do not know what is wrong, and i am not good at ruby.
Please help to check it.

Thanks. I do not have skype right now, maybe i can sign up one later. We can try on the post, if it is too many condition for this issue, i can sign up a Skype.
